ARG RUST_BUILDER_IMAGE
ARG RUNTIME_BASE_IMAGE
FROM ${RUST_BUILDER_IMAGE} AS build
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY rust ./rust
RUN cargo build --locked --release -p agent-trust-durable-orchestrator --bin agenttrust-transition-service

FROM ${RUNTIME_BASE_IMAGE}
COPY --from=build /src/target/release/agenttrust-transition-service /usr/local/bin/agenttrust-transition-service
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/agenttrust-transition-service"]
