ARG RUST_BUILDER_IMAGE
ARG RUNTIME_BASE_IMAGE
FROM ${RUST_BUILDER_IMAGE} AS build
WORKDIR /src
COPY Cargo.toml Cargo.lock ./
COPY rust ./rust
RUN cargo build --locked --release -p agent-trust-pack-marketplace --bin agenttrust-pack-marketplace-service

FROM ${RUNTIME_BASE_IMAGE}
COPY --from=build /src/target/release/agenttrust-pack-marketplace-service /usr/local/bin/agenttrust-pack-marketplace-service
USER nonroot:nonroot
EXPOSE 8090 9101
ENTRYPOINT ["/usr/local/bin/agenttrust-pack-marketplace-service"]
