locals {
  candidate_environment_variable_names = toset([
    "AGENT_TRUST_AGUI_VERIFY_KEY",
    "AGENT_TRUST_CODEOWNERS_SHA256",
    "AGENT_TRUST_CONSOLE_BASE_IMAGE",
    "AGENT_TRUST_CONTROL_API_URL",
    "AGENT_TRUST_DOCKER_BINARY",
    "AGENT_TRUST_DOCKER_SHA256",
    "AGENT_TRUST_ENVOY_BASE_IMAGE",
    "AGENT_TRUST_GH_BINARY",
    "AGENT_TRUST_GH_SHA256",
    "AGENT_TRUST_GIT_BINARY",
    "AGENT_TRUST_GIT_SHA256",
    "AGENT_TRUST_GIT_VERIFICATION_CONFIG_FILE",
    "AGENT_TRUST_JAVA_RUNTIME_IMAGE",
    "AGENT_TRUST_MAVEN_BUILDER_IMAGE",
    "AGENT_TRUST_NODE_BUILDER_IMAGE",
    "AGENT_TRUST_POSTGRES_CLIENT_IMAGE",
    "AGENT_TRUST_PYTHON_BASE_IMAGE",
    "AGENT_TRUST_PYTHON_BINARY",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_FILE",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_SHA256",
    "AGENT_TRUST_PYTHON_SHA256",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_DIRECTORY",
    "AGENT_TRUST_RUNTIME_BASE_IMAGE",
    "AGENT_TRUST_RUST_BUILDER_IMAGE",
    "AGENT_TRUST_UTILITY_BASE_IMAGE",
  ])
  evidence_environment_variable_names = toset([
    "AGENT_TRUST_DOCKER_BINARY",
    "AGENT_TRUST_DOCKER_SHA256",
    "AGENT_TRUST_GH_BINARY",
    "AGENT_TRUST_GH_SHA256",
    "AGENT_TRUST_GIT_BINARY",
    "AGENT_TRUST_GIT_PROVENANCE_KEYRING_FILE",
    "AGENT_TRUST_GIT_SHA256",
    "AGENT_TRUST_GIT_VERIFICATION_CONFIG_FILE",
    "AGENT_TRUST_PYTHON_BINARY",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_FILE",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_SHA256",
    "AGENT_TRUST_PYTHON_SHA256",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_DIRECTORY",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_MANIFEST_SHA256",
    "AGENT_TRUST_QUALIFICATION_SOURCE_DIRECTORY",
    "AGENT_TRUST_RELEASE_BINDING_KEYRING_FILE",
    "AGENT_TRUST_REVIEWER_KEYRING_FILE",
    "AGENT_TRUST_REVOCATION_CHECKPOINT_FILE",
    "AGENT_TRUST_REVOCATION_PUBLIC_KEY_FILE",
    "AGENT_TRUST_WORM_KEYRING_FILE",
  ])
  assurance_environment_variable_names = toset([
    "AGENT_TRUST_CARGO_BINARY",
    "AGENT_TRUST_CARGO_SHA256",
    "AGENT_TRUST_CLOSURE_PUBLIC_KEY_FILE",
    "AGENT_TRUST_DOCKER_BINARY",
    "AGENT_TRUST_DOCKER_SHA256",
    "AGENT_TRUST_GH_BINARY",
    "AGENT_TRUST_GH_SHA256",
    "AGENT_TRUST_GIT_BINARY",
    "AGENT_TRUST_GIT_PROVENANCE_KEYRING_FILE",
    "AGENT_TRUST_GIT_SHA256",
    "AGENT_TRUST_GIT_VERIFICATION_CONFIG_FILE",
    "AGENT_TRUST_PYTHON_BINARY",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_FILE",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_SHA256",
    "AGENT_TRUST_PYTHON_SHA256",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_DIRECTORY",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_MANIFEST_SHA256",
    "AGENT_TRUST_RELEASE_BINDING_KEYRING_FILE",
    "AGENT_TRUST_REVIEWER_KEYRING_FILE",
    "AGENT_TRUST_REVOCATION_CHECKPOINT_FILE",
    "AGENT_TRUST_REVOCATION_PUBLIC_KEY_FILE",
    "AGENT_TRUST_RUSTC_BINARY",
    "AGENT_TRUST_RUSTC_SHA256",
    "AGENT_TRUST_SIGNING_BROKER_CONFIG_FILE",
    "AGENT_TRUST_WORM_KEYRING_FILE",
  ])
  production_environment_variable_names = toset([
    "AGENT_TRUST_CLOSURE_PUBLIC_KEY_FILE",
    "AGENT_TRUST_DEPLOYMENT_CUTOVER_BROKER_CONFIG_FILE",
    "AGENT_TRUST_DEPLOYMENT_ENVIRONMENT_REFERENCE",
    "AGENT_TRUST_DOCKER_BINARY",
    "AGENT_TRUST_DOCKER_SHA256",
    "AGENT_TRUST_GH_BINARY",
    "AGENT_TRUST_GH_SHA256",
    "AGENT_TRUST_GIT_BINARY",
    "AGENT_TRUST_GIT_PROVENANCE_KEYRING_FILE",
    "AGENT_TRUST_GIT_SHA256",
    "AGENT_TRUST_GIT_VERIFICATION_CONFIG_FILE",
    "AGENT_TRUST_KUBECONFIG_FILE",
    "AGENT_TRUST_KUBECTL_BINARY",
    "AGENT_TRUST_KUBECTL_SHA256",
    "AGENT_TRUST_KUBERNETES_CONTEXT",
    "AGENT_TRUST_KUBERNETES_NAMESPACE",
    "AGENT_TRUST_PYTHON_BINARY",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_FILE",
    "AGENT_TRUST_PYTHON_RUNTIME_MANIFEST_SHA256",
    "AGENT_TRUST_PYTHON_SHA256",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_DIRECTORY",
    "AGENT_TRUST_PYTHON_WHEELHOUSE_MANIFEST_SHA256",
    "AGENT_TRUST_RELEASE_BINDING_KEYRING_FILE",
    "AGENT_TRUST_RELEASE_EVIDENCE_ROOT",
    "AGENT_TRUST_REVIEWER_KEYRING_FILE",
    "AGENT_TRUST_REVOCATION_CHECKPOINT_FILE",
    "AGENT_TRUST_REVOCATION_CHECKPOINT_LOCK_FILE",
    "AGENT_TRUST_REVOCATION_PROJECTION_CONFIG_FILE",
    "AGENT_TRUST_REVOCATION_PUBLIC_KEY_FILE",
    "AGENT_TRUST_WORM_KEYRING_FILE",
  ])
}

resource "github_actions_environment_variable" "candidate" {
  for_each      = var.candidate_environment_variables
  repository    = var.repository
  environment   = github_repository_environment.production_candidate.environment
  variable_name = each.key
  value         = each.value
}

resource "github_actions_environment_variable" "evidence" {
  for_each      = var.evidence_environment_variables
  repository    = var.repository
  environment   = github_repository_environment.production_evidence.environment
  variable_name = each.key
  value         = each.value
}

resource "github_actions_environment_variable" "assurance" {
  for_each      = var.assurance_environment_variables
  repository    = var.repository
  environment   = github_repository_environment.production_assurance.environment
  variable_name = each.key
  value         = each.value
}

resource "github_actions_environment_variable" "production" {
  for_each      = var.production_environment_variables
  repository    = var.repository
  environment   = github_repository_environment.production.environment
  variable_name = each.key
  value         = each.value
}
